Formulation of Apriori Constraints 

In [2]:
from constraints import *
import pandas as pd
from helpers import read_csv, load_pickled_data, pickle_data
import os
import matplotlib.pyplot as plt 
import plotly
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris


iris = load_iris()
DATASET_BASE = "dataset"
PICKLED_OBJS = "pickled_objs"

txs_classes:pd.DataFrame = read_csv(os.path.join(DATASET_BASE, "elliptic_txs_classes.csv"), ret_Dataframe=True)
txs_edgelist:pd.DataFrame = read_csv(os.path.join(DATASET_BASE, "elliptic_txs_edgelist.csv"), ret_Dataframe=True)
txs_features:pd.DataFrame =  read_csv(os.path.join(DATASET_BASE, "elliptic_txs_features.csv"), ret_Dataframe=True)


merge_feats_class = pd.merge(txs_features, txs_classes, on='txId').dropna()
#suppose we do that for localfeature51
merge_feats = merge_feats_class[merge_feats_class['Time step'] == 20].reset_index(drop=True)
iris = load_iris()
X, y = iris["data"], iris["target"]
names = iris["feature_names"]
data = pd.DataFrame(X, columns=names)



In [52]:
import pandas as pd
import numpy as np
from causalnex.discretiser.discretiser_strategy import MDLPSupervisedDiscretiserMethod
from sklearn.datasets import load_iris
iris = load_iris() 

# X, y = merge_feats_class["Local_feature_51"],  merge_feats_class["class"]

# data = pd.DataFrame(X, columns=merge_feats_class.columns)
# data["target"] = y
discretiser = MDLPSupervisedDiscretiserMethod(
{"min_depth": 5, "random_state": 2020, "min_split": 0, "dtype": int}
)

discretiser.fit(
feat_names=["Local_feature_51"],
dataframe=merge_feats[["Local_feature_51", "class"]],
target="class",
target_continuous=False,
)






MDLPSupervisedDiscretiserMethod(mdlp_args={'dtype': <class 'int'>,
                                           'min_depth': 5, 'min_split': 0,
                                           'random_state': 2020})

In [53]:
discretised_data = discretiser.transform(merge_feats[["Local_feature_51"]])
print(set(discretised_data.values.ravel()))

{1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18}


In [54]:

import collections
print(discretised_data)
print(discretised_data.values)
counter = collections.Counter(discretised_data.values.ravel())
print(counter)

      Local_feature_51
0                   11
1                   11
2                   11
3                   18
4                   11
...                ...
4282                 8
4283                11
4284                11
4285                11
4286                 1

[4287 rows x 1 columns]
[[11]
 [11]
 [11]
 ...
 [11]
 [11]
 [ 1]]
Counter({11: 3856, 1: 81, 13: 80, 18: 68, 3: 54, 8: 53, 5: 27, 16: 21, 15: 18, 10: 13, 2: 5, 14: 4, 7: 4, 12: 1, 9: 1, 6: 1})


In [43]:
print(merge_feats_class[["Local_feature_51", "class"]])

        Local_feature_51  class
0               0.042345      3
1               0.042345      3
2               0.042345      3
3               0.042345      2
4               0.042345      2
...                  ...    ...
202799          0.042345      3
202800          0.042345      3
202801          0.042345      3
202802          0.042345      3
202803          0.042345      3

[202804 rows x 2 columns]


<built-in method reshape of numpy.ndarray object at 0x00000201023549E0>


ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (0,) and requested shape (1,4287)

MinDivergenceModel(algorithm='CG',
          features=[<function is_valid_value at 0x0000020103BD4488>, <function in_given_range.<locals>.in_range at 0x0000020103D72D08>, <function in_given_range.<locals>.in_range at 0x0000020103D72D90>, <function in_given_range.<locals>.in_range at 0x0000020103D72E18>, <function in_given_range.<locals>.in_range at 0x0000020103D72EA0>],
          matrix_format='csr_matrix',
          samplespace=array([[ 0.04235],
       [ 0.04235],
       ...,
       [ 0.04235],
       [-3.74539]]),
          vectorized=True, verbose=0)

[0.         0.         0.         0.         0.03723635]
[[0.08       0.02146    0.02729181 0.90179613 0.01516212]]
